# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa86c41752c1cf1ae4592c46112cb159094cf46516b6ae302c6b42cf39e6032f224570882fa86354beed4e21d4639603ec2e8bc50d20ed8c0229bd418fbba301

test:
  secret_key_base: 8dc8679aedebaa14abae6aec2129c2827ef254a453e2610ddab1324527ceb1e3702445f8a3fd37395d2f6cf8c55de4d145485fa78e87f91d1bd0d8ece9267344

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
